### ISSUE TITLE
Late execution by Safari or userscript manager causes `unconfigurable property` exception

### ISSUE THREAD

**Issue by fortinmike** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#102]
Looks like YouTube defines ytInitialData and (and undoubtedly other properties) as [non-configurable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#modifying_a_property) which causes `Object.defineProperty` to fail with the error: `TypeError: Attempting to change configurable attribute of unconfigurable property.`

This looks unavoidable to me... any insight on how this might be bypassed?

I only tested this in Safari. Do other browsers not respect the non-configurable nature of this property, or is something else causing this exception in Safari?

**Comment by drunkwinter** [comment]
The only reason I can think of is that Safari or your userscript manager execute our userscript later than usual. I also experienced this while putting some of the code in a `setTimeout` for testing.

Will investigate if this can be avoided, but don't hold your breath.

**Comment by drunkwinter** [comment]
@VGisHere Just out of curiosity, what userscript manager are you currently using?

**Comment by VGisHere** [comment]
I’m using the ‘hyperweb’ extension to load any JS’.

**Comment by drunkwinter** [comment]
Hey guys, a little update, so we are working on a new version that doesn't use `Object.defineProperty`. This means that this bug is hopefully gonna be solved. But we are gonna need some confirmation from you that this actually works.

Can you guys to test this unofficial build and confirm that all is working well and that this bug is solved?

[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7800675/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by fortinmike** [comment]
Just tested it and it seems to work fine now, at least with the Userscripts app/manager. Thanks so much for taking the time to investigate and fix this; I didn't expect a resolution anytime soon.

I'll let you know and try to help diagnose if I find any issue with it, but so far it works! :)

**Comment by ThiemeH** [comment]
Just tested with Userscripts Safari. Works like a charm!

**Comment by drunkwinter** [comment]
Fixed in #108
