### ISSUE TITLE
Youtube Music support

### ISSUE THREAD

**Issue by ArjixWasTaken** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#121]
Would be nice if this script could also run on youtube music.
It might sound like a weird request since it is youtube music, but if you didn't already know, you can play normal videos on it.

**Comment by zerodytrash** [comment]
Thank you for pointing this out @ArjixWasTaken , i didn't know that because i have never used youtube music.
A short test shows that just the inclusion of `music.youtube.com` works perfectly.

=> `// @match https://music.youtube.com/*`

The following tweaks would be optional:
- Use clientName `WEB_REMIX`
(Thats youtube music's own client name. There are a few differences in the response, but youtube music also processes the `WEB` response correctly)
- Adapt unlock notification

Example Music Video: https://music.youtube.com/watch?v=dqRZDebPIGs&list=RDAMVMdqRZDebPIGs

**Comment by bachig26** [comment]
> => `// @match https://music.youtube.com/*`
> 
> The following tweaks would be optional:
> 
> * Use clientName `WEB_REMIX`
>   (Thats youtube music's own client name. There are a few differences in the response, but youtube music also processes the `WEB` response correctly)
> * Adapt unlock notification

I wanted to try this myself, but I have a doubt that will it be enough to change the clientName from 'WEB_CREATOR' to `WEB_REMIX` in Strategy 2 (at line 575) or need to do anything else or create a new Strategy (additional lines).
also, I couldn't able find the clientVersion number for `WEB_REMIX`.

**Comment by zerodytrash** [comment]
@bachig26 Have just implemented the todos https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1fafebd8a4cd9d2625a89fa1dbdeff42532966a3

`WEB_CREATOR` remains `WEB_CREATOR` because this client name is relevant for the strategy. Strategy 1 and 3 now use `WEB_REMIX`, which is read from the Youtube configuration (Ytcfg) after a little refactoring of the existing code. The same applies to the client version number.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/eecb5ab5d989518981a2b3eae222c5be48462ce9/src/components/unlocker.js#L20
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/eecb5ab5d989518981a2b3eae222c5be48462ce9/src/components/unlocker.js#L21

Here is a pre-release version of the changes: [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/8011356/Simple-YouTube-Age-Restriction-Bypass.user.zip)
Will release the update in the next few days after some tests.

**Comment by zerodytrash** [comment]
This is now done. If there are any problems, simply create a new issue.

**Comment by ArjixWasTaken** [comment]
Thx so much
