### ISSUE TITLE
Script seems to not be working again

### ISSUE THREAD

**Issue by ner00** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#17]
Some age restricted videos are being blocked permanently, regardless of being logged in or not.
One such video, previously mentioned in https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/15 : https://www.youtube.com/watch?v=rR8s72aouNE

Blocked even while logged in.

Other videos can still be bypassed, like: https://www.youtube.com/watch?v=ppTiXcBYq_A

Curiously, does who cannot be bypassed by this video also seem to not be working with Invidious.

**Comment by zerodytrash** [comment]
The video you mentioned generally can not be bypassed. Even youtube-dl fails. See https://github.com/ytdl-org/youtube-dl/issues/28578 for more details. This is because YouTube requires a valid session from a confirmed google account for some videos.

However, other videos can still be unlocked. For example: https://www.youtube.com/watch?v=duZsTr6_-mg

If you have any other videos where the bypass doesn't work, feel free to post them here.

**Comment by ner00** [comment]
> a confirmed google account

Event after reading the issue in youtube-dl I'm not clear what this means.
I just see the exact same age verification block on all videos, some will be unlocked and some won't, I'm not sure what the distinction is here.

**Comment by ner00** [comment]
There doesn't seem to be any workaround for this. I caved in and sent my documents to Google.
