### ISSUE TITLE
UpdateURL not sufficient

### ISSUE THREAD

**Issue by yash-fn** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#199]
### What happened?

supportURL doesn't update the link in Userscripts app for ios. You have to use updateURL. So for example, adding following to header in script will allow users to automatically update their script to the latest version directly from the app/extension.

```js
// @updateURL https://raw.githubusercontent.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/main/dist/Simple-YouTube-Age-Restriction-Bypass.user.js
```

### Platform

Userscript

### Version

2.5.7

### What browser are you on?

Safari

### Browser version

Latest

### Link to the video

All videos

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, an issue was already made previously about this (issue #90). Although we already decided on not including this configuration, for the reasons stated in that issue, we might still reconsider this.

Recently I've seen issues where people still were using old versions, due to auto-update not working. Either because they are using a userscript manager which does not support updateURL being downloadURL or they have installed the version from the GitHub Releases page, which means the downloadURL will always point to that same version.
