### ISSUE TITLE
Account Proxy Server 

### ISSUE THREAD

**Issue by cottonzero** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#40]
wondering if you could help i am trying to run my own account proxy server, but having some troubles.

could you please give brief overview of how you think this should be working, do we run a script to install the APServer or something else

thanks in advanced
CZ

**Comment by zerodytrash** [comment]
Hi,
The account proxy server is a NodeJS application. First you need to install the dependencies with `npm install`.  After that create the configuration file (`.env`). The required attributes can be found in the [README](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/main/account-proxy/README.md). In order to retrieve age-restricted videos, you need to set the cookies of a youtube (google) account in the configuration. Only two cookies are required (`SAPISID` and `__Secure-3PSID`. If the account is not verified, you must use an IP located in the USA. For this you can set a HTTP proxy.

I will add the info to the readme.
Let me know if you have a specific question about the account proxy.
