### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by Useless-Panda** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#42]
Just wanted to say thank you for not giving up on this script

**Comment by alsoGAMER** [comment]
Honestly, I don't get the point of all of this effort, all that is needed to permanently ""bypass"" that check is a credit/debit card, you need to insert the card data once and you're good to go, that thing won't show up anymore.

**Comment by Blumlaut** [comment]
it's a matter of privacy, some people generally dont want to give a gigantic advertising company who dropped the internal "Don't be evil" motto their private information, be it credit card or personal id.

**Comment by alsoGAMER** [comment]
> it's a matter of privacy, some people generally dont want to give a gigantic advertising company who dropped the internal "Don't be evil" motto their private information, be it credit card or personal id.

Well, nobody forces you to give them your real id/cc, you can just generate a random cc and here you go.

**Comment by Blumlaut** [comment]
> 
> 
> > it's a matter of privacy, some people generally dont want to give a gigantic advertising company who dropped the internal "Don't be evil" motto their private information, be it credit card or personal id.
> 
> Well, nobody forces you to give them your real id/cc, you can just generate a random cc and here you go.

What a silly reply, and then you risk getting your account banned if they catch on, theres a reason this bypass exists, you are just looking for excuses to be a smartass.

**Comment by alsoGAMER** [comment]
> > > it's a matter of privacy, some people generally dont want to give a gigantic advertising company who dropped the internal "Don't be evil" motto their private information, be it credit card or personal id.
> > 
> > 
> > Well, nobody forces you to give them your real id/cc, you can just generate a random cc and here you go.
> 
> What a silly reply, and then you risk getting your account banned if they catch on, theres a reason this bypass exists, you are just looking for excuses to be a smartass.

I'm not looking for anything, I just said that for me personally, this thing is a waste of time, but this is only my opinion, as I see, 322 people found this useful and starred it, if that's enough for the project maintainer, well.. good for them.

**Comment by LukeSeers** [comment]
> Honestly, I don't get the point of all of this effort, all that is needed to permanently ""bypass"" that check is a credit/debit card, you need to insert the card data once and you're good to go, that thing won't show up anymore.

Since your from Italy, surely you wish to keep your democracy? Privacy is a core human right and also a key part of democracy. 

It always starts off small like giving your credit card to a private company to prove your "age/identity" for something very little then it will expand very fast. A great example is the UK, The people of the UK are unaware with what's happening and soon their internet will be censored like china and more people will be arrested for "checking their thinking". 

To add a tad bit more. The GDPR was suppose to protect the people from private companies slurping their data and used for political gain. Now the EU/UK wants to give them private companies your data. If you ask me, it's a bit backwards. History always repeats it self. We should know by now that if you give the gov a inch they would turn it into a mile.

You might be asking how is credit/debit card useful? well combined with the rest of the data they have collected from you which is not just on google websites, but across many websites since people use google services on their websites. They can easily use that and figure out what type of political minded people use that type of bank etc , thus they could use that to sway political voters to their advantage. As I mentioned above before this has already happened and it will again. 

> Well, nobody forces you to give them your real id/cc, you can just generate a random cc and here you go.

I would rather not be done for fraud and put in the clink for 10 years + a fine for a real crime.

**Comment by ArjixWasTaken** [comment]
> > it's a matter of privacy, some people generally dont want to give a gigantic advertising company who dropped the internal "Don't be evil" motto their private information, be it credit card or personal id.
> 
> Well, nobody forces you to give them your real id/cc, you can just generate a random cc and here you go.

Google is not that dumb, it verifies if a card is valid and exists.
