### ISSUE TITLE
Quality of code concerns

### ISSUE THREAD

**Issue by ArjixWasTaken** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#49]
It's weird how you use the null safety calls (aka Optional chaining), but you use var everywhere as well...
Like, unless you want to redefine that variable and it is a global one, var is useless.

99% of the variables can be converted to constants.

**Comment by MinePlayersPE** [comment]
true, we even mentioned how much of a nightmare the script is in https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/pull/45#issuecomment-894371707 😅

**Comment by zerodytrash** [comment]
Hi, thanks for your feedback.

> It's weird how you use the null safety calls (aka Optional chaining)

With optional chaining:
`var singleColumnWatchNextContents = contents.singleColumnWatchNextResults?.results?.results?.contents;`

Without optional chaining:
```
var singleColumnWatchNextContents = null
if(contents && contents.singleColumnWatchNextResults && contents.singleColumnWatchNextResults.results && contents.singleColumnWatchNextResults.results.results && contents.singleColumnWatchNextResults.results.results.contents) {
     singleColumnWatchNextContents = contents.singleColumnWatchNextResults.results.results.contents
}
```
Would that be better? Or are there other alternatives?

> 99% of the variables can be converted to constants.

Yes, I will change the variables to constants on the next update.

I think it's a waste of time to care about code conventions in such scripts. On the one hand, because it's just a "hack" that might not work next week, and on the other hand, because further development based on this code is completely pointless. The approach to intercept and manipulate JSON data is very exotic and also not really maintainable. Especially because the data that youtube processes has very complex structures that are also constantly changing. 

Change my mind :)

**Comment by ArjixWasTaken** [comment]
> I think it's a waste of time to care about code conventions in such scripts.

It's not a code convention, it's a safety measure.
By using vars everywhere you are bound to get into a weird error that doesn't make sense.
Since vars are global at all times.

**Comment by zerodytrash** [comment]
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/fb3b521790883c6aee86545eb2458829c5cf9713

Changed all variables to const and let :)

**Comment by ArjixWasTaken** [comment]
Great!
