### ISSUE TITLE
Not working with Membership content 

### ISSUE THREAD

**Issue by MadATYoutube** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#50]
So basically it dosen't work with member only content that is age restricted 
Hope this can be fixed

**Comment by zerodytrash** [comment]
yes, thats because the `/youtubei/v1/player` request is made without any authentication. We can try to make the request in the context of the logged in user (with Cookies + SAPISIDHASH Header). But I'm not sure if the `clientScreen`:`EMBED` bypass works with member only content, since such videos are usually not embeddable.

It would probably be better to implement a second bypass with `client`:`WEB_CREATOR`. This client can also retrieve non-embeddable + age-restricted videos with a valid user session. See https://github.com/yt-dlp/yt-dlp/pull/600

I will put this on the to do list :)

**Comment by zerodytrash** [comment]
A new bypass method is now available in the latest release. Maybe it works with membership content. Can you test this @MadATYoutube

**Comment by MadATYoutube** [comment]
I unfortunately cannot test it right now
Sorry

**Comment by zerodytrash** [comment]
okay, then i'll close the issue. if there are still problems at some point, just open it again.

**Comment by MadATYoutube** [comment]
finally got around to testing it but unfortunately, it does not work
<img width="1919" alt="FFFF" src="https://user-images.githubusercontent.com/89040819/140539131-1fe16ae6-4e87-4b5d-809f-69b931b56a02.PNG">
