### ISSUE TITLE
Optional chaining wrongly used

### ISSUE THREAD

**Issue by superpoincare** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#54]
The line

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/2e1b1fadec000067f375dbf828c420a2babd21f3/Simple-YouTube-Age-Restriction-Bypass.user.js#L500

should rather be:

```javascript
if(window?.GM_info?.scriptHandler === "Greasemonkey") { 
```

Otherwise if  I inject your code in my own extension (without using Greasemonkey), it gives an error and doesn't work.

**Comment by zerodytrash** [comment]
hi,

unfortunately your suggestion doesn't work with greasemonkey in firefox, because the `GM_info` variable can't be accessed through the window. i made the following change instead:

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/bd954b3f230d9bd1b2f2e063b18ab228517da3a8/Simple-YouTube-Age-Restriction-Bypass.user.js#L502

will this fix your problem?

**Comment by superpoincare** [comment]
Yeah this will do.

**Comment by zerodytrash** [comment]
nice
