### ISSUE TITLE
Black screen for a few seconds when using [multiple] adblockers

### ISSUE THREAD

**Issue by Harry-Pootha** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#83]
Hi,

ever since installing your script I've been getting around 5+s of blackscreen with a advertisement title on top. I found that it most likely occurs because of my adblock extensions. Emphasis on it being multiple ones.

Currently these ones are installed:
- https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg
- https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb
- https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

From what I can gather the main culprit seems to be the last one in that list.

**Comment by Harry-Pootha** [comment]
I've had a look into the script and may have found a solution which at least works on my system and one of a friend of mine.

In attachInitialDataInterceptor you keep track of the setter for ytInitialPlayerResponse, set by what are most likely adblockers. If multiple setters exist (due to there being multiple extensions) only the last one will be called later on. So the extensions may wait for a call of the setter to continue which never happens. So instead we can keep track of all the setters and calling all of them in the right order.

Of course for the getter it doesn't matter if only the last one is triggered.

**Comment by Harry-Pootha** [comment]
For now I've made these changes quick and dirty locally. You can see them in this pastebin:
https://pastebin.com/pCBRmnBD

**Comment by DrunkWinter** [comment]
I thought about fixing this while refactoring a while ago.. 
But didn't bother since I never really thought someone would use so many adblockers. Anyway probably a good practice to assume an infinite amount :P

Above pull request needs some testing.

On a side note.. Why would you need that many adblockers, when [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) probably does a better job alone, than all of them combined?

**Comment by Harry-Pootha** [comment]
To be honest I don't rightly remember why I started using that many adblockers. I think it was in the past when there was no full feature parity between the different adblockers. uBlock is even already installed and I just missed it in my list. Maybe a good time to clean up some of these 😅 

But great to see this fixed. If not for me then for others (like the guy I tested with)

**Comment by DrunkWinter** [comment]
I'm gonna hold off on this one. 

After thinking about it, if userscripts/extensions also keep track of one another (which many do), this could potentially result in a function getting called twice or more, which could result in some weird behavior. Therefore it seems that this solution won't work as originally intended.  On top of that it doesn't seem our responsibility to keep track of every extension, except the one after our execution, which in turn should keep track of the next, creating a chain. Not doing so, will naturally cause a compatibility issue and should be fixed by the respective developers.

I will be closing the pull request if anybody doesn't have any objections.

**Comment by drunkwinter** [comment]
Fixed in #108
